packages:
  - apps/*
  - packages/*
  - extensions/*

catalog:
  '@changesets/cli': ^2.29.8
  '@codemirror/lang-angular': ^0.1.3
  '@codemirror/lang-cpp': ^6.0.2
  '@codemirror/lang-css': ^6.2.1
  '@codemirror/lang-go': ^6.0.1
  '@codemirror/lang-html': ^6.4.9
  '@codemirror/lang-java': ^6.0.1
  '@codemirror/lang-javascript': ^6.2.2
  '@codemirror/lang-json': ^6.0.1
  '@codemirror/lang-less': ^6.0.2
  '@codemirror/lang-lezer': ^6.0.1
  '@codemirror/lang-liquid': ^6.2.1
  '@codemirror/lang-markdown': ^6.2.5
  '@codemirror/lang-php': ^6.0.1
  '@codemirror/lang-python': ^6.1.6
  '@codemirror/lang-rust': ^6.0.1
  '@codemirror/lang-sass': ^6.0.2
  '@codemirror/lang-sql': ^6.7.0
  '@codemirror/lang-vue': ^0.1.3
  '@codemirror/lang-wast': ^6.0.2
  '@codemirror/lang-xml': ^6.1.0
  '@codemirror/lang-yaml': ^6.1.1
  '@codemirror/language': ^6.10.2
  '@codemirror/state': ^6.4.1
  '@codemirror/view': ^6.30.0
  '@monaco-editor/react': ^4.6.0
  '@rollup/plugin-alias': ^6.0.0
  '@rollup/plugin-commonjs': ^29.0.0
  '@rollup/plugin-json': ^6.0.1
  '@rollup/plugin-node-resolve': ^16.0.3
  '@rollup/plugin-terser': ^0.4.4
  '@rollup/plugin-typescript': ^12.3.0
  '@rollup/pluginutils': ^5.3.0
  '@types/node': ^25.0.3
  '@types/parsimmon': ^1.10.8
  '@types/react': ^19.2.7
  '@types/react-dom': ^19.2.3
  '@vitejs/plugin-react': ^5.1.2
  '@xterm/addon-fit': ^0.11.0
  '@xterm/addon-unicode11': ^0.9.0
  '@xterm/addon-web-links': ^0.12.0
  '@xterm/addon-webgl': ^0.19.0
  '@xterm/xterm': ^6.0.0
  ansi-colors: ^4.1.3
  codemirror: ^6.0.1
  comlink: ^4.4.2
  cross-env: ^10.1.0
  deepmerge: ^4.3.1
  eventemitter3: ^5.0.1
  fast-deep-equal: ^3.1.3
  immer: ^11.1.3
  is-promise: ^4.0.0
  jotai: ^2.16.1
  json5: ^2.2.3
  jszip: ^3.10.1
  list: ^2.0.19
  monaco-editor: ^0.55.1
  parsimmon: ^1.18.1
  preact: ^10.23.1
  react: ^19.2.3
  react-dom: ^19.2.3
  rollup: ^4.54.0
  rollup-plugin-delete: ^3.0.2
  rollup-plugin-dts: ^6.3.0
  rollup-plugin-peer-deps-external: ^2.2.4
  rollup-plugin-string: ^3.0.0
  rollup-plugin-typescript2: ^0.36.0
  synchronous-promise: ^2.0.17
  thememirror: ^2.0.1
  tsup: ^8.5.1
  turbo: ^2.7.2
  typescript: ^5.9.3
  unzipit: ^1.4.3
  valibot: ^1.2.0
  vite: ^7.3.0
  vite-plugin-html: ^3.2.2
  vite-plugin-singlefile: ^2.3.0

catalogMode: strict

onlyBuiltDependencies:
  - esbuild
